# Generated by Django 3.0.6 on 2020-05-18 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Get_date', models.DateField(default=datetime.datetime(2020, 5, 18, 0, 13, 58, 687674, tzinfo=utc))),
                ('Animal_kind', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=3)),
                ('Photo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
