# Generated by Django 3.0.6 on 2020-05-18 00:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='Breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='Get_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 18, 0, 20, 24, 544948, tzinfo=utc)),
        ),
    ]
